/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ChapterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "chapter";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type TaxonomyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "taxonomy";
};

export type Unit = {
  _id: string;
  _type: "unit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  chapter: ChapterReference;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  summary?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & CodeBlock)
    | ({
        _key: string;
      } & UnitEmbed)
  >;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & TaxonomyReference
  >;
  tags?: Array<
    {
      _key: string;
    } & TaxonomyReference
  >;
  status: "draft" | "published";
  publishedAt?: string;
  seo?: Seo;
  unitNumber?: number;
  order?: number;
  legacyWordPressId?: number;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type UnitEmbed = {
  _type: "unitEmbed";
  embedType: "embed" | "figma" | "audio" | "model";
  src: string;
  href?: string;
  linkText?: string;
};

export type Taxonomy = {
  _id: string;
  _type: "taxonomy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  kind: "category" | "tag";
  description?: string;
};

export type CodeBlock = {
  _type: "codeBlock";
  code: string;
  language?:
    | "text"
    | "javascript"
    | "typescript"
    | "jsx"
    | "tsx"
    | "html"
    | "css"
    | "json"
    | "csharp"
    | "python"
    | "shell";
  filename?: string;
};

export type Chapter = {
  _id: string;
  _type: "chapter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  subtitle?: string;
  summary?: string;
  dateRange?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  legacyWordPressCategoryId?: number;
  order?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  bio?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ChapterReference
  | SanityImageAssetReference
  | AuthorReference
  | TaxonomyReference
  | Unit
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | UnitEmbed
  | Taxonomy
  | CodeBlock
  | Chapter
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../../src/lib/sanity/queries.ts
// Variable: chapterBySlugQuery
// Query: *[_type == "chapter" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    subtitle,    summary,    dateRange,    logo {      asset->{ _id, url },      alt    }  }
export type ChapterBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  summary: string | null;
  dateRange: string | null;
  logo: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: null;
  } | null;
} | null;

// Source: ../../src/lib/sanity/queries.ts
// Variable: unitsByChapterSlugQuery
// Query: *[    _type == "unit" &&    chapter->slug.current == $slug &&    coalesce(status, "published") == "published"  ]    | order(coalesce(order, 999) asc, coalesce(unitNumber, 999) asc, title asc) {    _id,    title,    "slug": slug.current,    summary,    order,    unitNumber,    publishedAt,    status,    thumbnail {      asset->{ _id, url },      alt    }  }
export type UnitsByChapterSlugQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  order: number | null;
  unitNumber: number | null;
  publishedAt: string | null;
  status: "draft" | "published";
  thumbnail: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
  } | null;
}>;

// Source: ../../src/lib/sanity/queries.ts
// Variable: unitBySlugsQuery
// Query: *[    _type == "unit" &&    slug.current == $unitSlug &&    chapter->slug.current == $chapterSlug &&    coalesce(status, "published") == "published"  ][0]{    _id,    title,    "slug": slug.current,    summary,    order,    unitNumber,    publishedAt,    status,    body[]{      ...,      _type == "image" => {        ...,        asset->{ _id, url }      },      _type == "unitEmbed" => {        ...      }    },    thumbnail {      asset->{ _id, url },      alt    },    author->{      name,      "slug": slug.current,      bio,      avatar {        asset->{ _id, url },        alt      }    },    categories[]->{      _id,      title,      "slug": slug.current,      kind    },    tags[]->{      _id,      title,      "slug": slug.current,      kind    },    "seo": {      "title": coalesce(seo.metaTitle, title, ""),      "description": coalesce(seo.metaDescription, summary, ""),      "image": coalesce(seo.ogImage, thumbnail) {        asset->{ _id, url },        alt      },      "noIndex": seo.noIndex == true    },    chapter->{      _id,      title,      "slug": slug.current    }  }
export type UnitBySlugsQueryResult = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  order: number | null;
  unitNumber: number | null;
  publishedAt: string | null;
  status: "draft" | "published";
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "codeBlock";
        code: string;
        language?:
          | "csharp"
          | "css"
          | "html"
          | "javascript"
          | "json"
          | "jsx"
          | "python"
          | "shell"
          | "text"
          | "tsx"
          | "typescript";
        filename?: string;
      }
    | {
        asset: {
          _id: string;
          url: string;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        _key: string;
        _type: "unitEmbed";
        embedType: "audio" | "embed" | "figma" | "model";
        src: string;
        href?: string;
        linkText?: string;
      }
  > | null;
  thumbnail: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
  } | null;
  author: {
    name: string;
    slug: string;
    bio: string | null;
    avatar: {
      asset: {
        _id: string;
        url: string;
      } | null;
      alt: string;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
    kind: "category" | "tag";
  }> | null;
  tags: Array<{
    _id: string;
    title: string;
    slug: string;
    kind: "category" | "tag";
  }> | null;
  seo: {
    title: string;
    description: string | "";
    image:
      | {
          asset: {
            _id: string;
            url: string;
          } | null;
          alt: string;
        }
      | {
          asset: {
            _id: string;
            url: string;
          } | null;
          alt: string | null;
        }
      | null;
    noIndex: boolean | false;
  };
  chapter: {
    _id: string;
    title: string;
    slug: string;
  };
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "chapter" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    subtitle,\n    summary,\n    dateRange,\n    logo {\n      asset->{ _id, url },\n      alt\n    }\n  }\n': ChapterBySlugQueryResult;
    '\n  *[\n    _type == "unit" &&\n    chapter->slug.current == $slug &&\n    coalesce(status, "published") == "published"\n  ]\n    | order(coalesce(order, 999) asc, coalesce(unitNumber, 999) asc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    order,\n    unitNumber,\n    publishedAt,\n    status,\n    thumbnail {\n      asset->{ _id, url },\n      alt\n    }\n  }\n': UnitsByChapterSlugQueryResult;
    '\n  *[\n    _type == "unit" &&\n    slug.current == $unitSlug &&\n    chapter->slug.current == $chapterSlug &&\n    coalesce(status, "published") == "published"\n  ][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    order,\n    unitNumber,\n    publishedAt,\n    status,\n    body[]{\n      ...,\n      _type == "image" => {\n        ...,\n        asset->{ _id, url }\n      },\n      _type == "unitEmbed" => {\n        ...\n      }\n    },\n    thumbnail {\n      asset->{ _id, url },\n      alt\n    },\n    author->{\n      name,\n      "slug": slug.current,\n      bio,\n      avatar {\n        asset->{ _id, url },\n        alt\n      }\n    },\n    categories[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      kind\n    },\n    tags[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      kind\n    },\n    "seo": {\n      "title": coalesce(seo.metaTitle, title, ""),\n      "description": coalesce(seo.metaDescription, summary, ""),\n      "image": coalesce(seo.ogImage, thumbnail) {\n        asset->{ _id, url },\n        alt\n      },\n      "noIndex": seo.noIndex == true\n    },\n    chapter->{\n      _id,\n      title,\n      "slug": slug.current\n    }\n  }\n': UnitBySlugsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
